### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by katherinelyx** [TomHeaven/nudt_thesis#10]
你好，前辈。感谢您的贡献。
我在编译时出现了一系列错误，如下图：
![捕获](https://user-images.githubusercontent.com/37907650/149063555-5036fe35-1f3b-40cf-9145-bf0335fc17de.JPG)
-系统是win10，texlive2019，texstudio
-已经安装ttf字体。

**Comment by TomHeaven** [comment]
看齐来你的texlive环境没有安装完成，缺包，请重新安装再试试。
参考：https://techoverflow.net/2014/02/07/latex-and-specialchinese-unicode-characters/
