### ISSUE TITLE
经过检查发现首页上方的四个条目不对齐

### ISSUE THREAD

**Issue by RPZ97** [TomHeaven/nudt_thesis#12]
推荐修改nudtpaper.cls文件527行 \begin{tabular}处的代码如下：
`
    \begin{tabular}{clcll}
    \makebox[1.2cm][s]{\ 分类号\ }  & \entry{1}{3.2cm}{\@classification} & \hspace*{4.8cm} & 学号 & \entry{1}{3.2cm}{\@serialno} \\[5mm]   \makebox[1.2cm][s]{\ U\ D\ C\ }& \entry{1}{3.2cm}{\@UDC} &          \hspace*{4.8cm} & 密级 & \entry{1}{3.2cm}{\@confidentiality}
    \end{tabular}
`

**Comment by TomHeaven** [comment]
确有此问题。已经将修改提交入master：https://github.com/TomHeaven/nudt_thesis/commit/8b3a2bddae76af29673ece178c474bd225b39bdc

**Comment by TomHeaven** [comment]
已修复。

**Comment by TomHeaven** [comment]
已修复。

**Comment by TomHeaven** [comment]
已修复

**Comment by TomHeaven** [comment]
已经修复
