### ISSUE TITLE
关于仿宋字体找不到的问题

### ISSUE THREAD

**Issue by ConfVD** [TomHeaven/nudt_thesis#15]
仿宋安装以后编译提示找不到FangSong_GB2312
解决方法：将字体文件里面的仿宋_GB2312更名成FangSong_GB2312
（记忆有点久远，根据前端的报错大家自己确认更改的名称即可）
环境：TexStudio+Miktex

**Comment by TomHeaven** [comment]
Miktex我没测试过，希望对其他同学有帮助。
