### ISSUE TITLE
关于图标题角标的问题

### ISSUE THREAD

**Issue by GeneralLi95** [TomHeaven/nudt_thesis#4]
如果在正文图标题进行了引用，则图目录处，同样也出现了角标，这样一来，参考文献的角标顺序从图表标题处就开始了，导致正文处第一处引用显示的已经是，[4]或[7][8]，不知道这个问题是否需要解决，该如何解决呢。

**Comment by TomHeaven** [comment]
图表标题用[短标题]{长标题}，短标题只会在图表目录中出现，里面不要放引用。长标题只会在正文中出现，可以放引用。

**Comment by GeneralLi95** [comment]
@TomHeaven 明白了，感谢师兄
