### ISSUE TITLE
xelatex编译慢且电脑发热严重

### ISSUE THREAD

**Issue by DeathGun007** [TomHeaven/nudt_thesis#7]
师兄您好，

   我在用你做的科大论文模板遇到个问题， 我的环境是 TeX live2018 + TeXstudio (Mac OS)，用XelaTeX运行thesis.tex 文件。

   问题是：比如运行绘图包 tikz or  pgfplot画个流程图，编译很慢，电脑发热很严重，风扇呼呼转。但是画英文图的时候（用pgfLaTeX）就没有，我在网上看到有人说是字体缓存的原因，我用的是ttf字体，但是我也不知道怎么解决。请问您遇到过相关的问题吗？ 感谢

NUDT 
Guishan

**Comment by DeathGun007** [comment]
我还用到了 \usetikzlibrary{external} 模式，是否是由于这个的影响？

**Comment by TomHeaven** [comment]
我用的也是macOS。2018确实比较慢的，建议用MacTex 2015，这个版本貌似可以增量编译，第一次慢，后面编译就很快（全文几秒钟）。

**Comment by DeathGun007** [comment]
感谢您的解答，请问mac TeX2015 是指的TeXLive 2015吗

**Comment by TomHeaven** [comment]
是的。不过mac版的就叫MacTex。网上不好找了，我分享了一个链接:https://pan.baidu.com/s/1YhloP6V72CqGOLwXCH-bhw  密码:jmd5

**Comment by DeathGun007** [comment]
感谢大神的解答，解决了我的问题，另外external模式确实对编译有影响，可以先关闭，等画的图满意后再输出external pdf，希望对各位同学也有帮助。 此issue可以关闭了
