### ISSUE TITLE
专硕可以用吗？

### ISSUE THREAD

**Issue by dongfangxier** [TomHeaven/nudt_thesis#8]
好像模板不太一样，有没有专硕的模板？

**Comment by TomHeaven** [comment]
不太了解专硕的论文模版。我估计至少正文部分是一样的，如果你能提供专硕的word模版，我可以尝试制作。

**Comment by dongfangxier** [comment]
@TomHeaven 我看到只有封面和页眉不太一样，我打印前替换掉就可以，谢谢你的模板
![image](https://user-images.githubusercontent.com/56461530/100443697-27e69900-30e5-11eb-9228-909454b1255a.png)
